image: node:22-slim

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/

pages:
  script:
    - npm ci
    - npm run build
    - mv _site public
  artifacts:
    paths:
      - public
  only:
    - master
